### ISSUE TITLE
Not compatible with eclipse 2019-09

### ISSUE THREAD

**Issue by mnlipp** [hallvard/plantuml#101]
Trying to install this from the Eclipse Marketplace in Eclipse 2019-09 I get a message that this plugin is not compatible with this version of Eclipse.

**Comment by mnlipp** [comment]
For all those who depend on this plugin as much as I do, I have built it using Eclipse 2019-09 and created a temporary [update site](https://raw.githubusercontent.com/mnlipp/plantuml/master/net.sourceforge.plantuml.eclipse.p2-repository/) that can be used until "the real stuff" becomes available again.

**Comment by hallvard** [comment]
I think the problem is the metadata in the marketplace, not my update site @ hallvard.github.io/plantuml

- Hallvard

12. okt. 2019 16:59 skrev "Michael N. Lipp" <notifications@github.com>:

For all those who depend on this plugin as much as I do, I have built it using Eclipse 2019-09 and created a temporary update site<https://raw.githubusercontent.com/mnlipp/plantuml/master/net.sourceforge.plantuml.eclipse.p2-repository/> that can be used until "the real stuff" becomes available again.

-

**Comment by anb0s** [comment]
@mnlipp no need for new update site! The plugin is working with 2019-03 / 06 / 09 just use the right update site: https://hallvard.github.io/plantuml

The problem is with install from marketplace only:
https://marketplace.eclipse.org/content/plantuml-plugin

Here the versions are selected (supported): 2018-12 (4.10), 2018-09 (4.9), Photon (4.8), Oxygen (4.7), Neon (4.6), Mars (4.5), Luna (4.4)

@hallvard: If you select the missing 2019-03 (4.11), 2019-06 (4.12) and latest 2019-09 (4.13) in marketplace as supported, then it will automatically select the next version for you when released 
 (e.g. 2019-12) and you will receive email about it from marketplace for verification.

**Comment by hallvard** [comment]
I've updated the marketplace now
