### ISSUE TITLE
Eclipse Marketplace Update

### ISSUE THREAD

**Issue by wlfbck** [hallvard/plantuml#125]
It seems that the version available via the marketplace is still 1.1.22 (or atleast it is what is offered in Eclipse 2021-03).
It would be great if you could update it, because i'm running into issues with https://github.com/plantuml-stdlib/C4-PlantUML where the include via URL doesn't work since they use tags which were added later to plantuml.

Small sidenote: In your readme.md you mention 1.1.25, but under releases there is only 1.1.24. Not clear to me if 1.1.25 is just what is currently worked on or if there is a release missing :)

**Comment by hallvard** [comment]
I’m finalizing 1.1.25 now, I’ll update Marketplace when releasing (this week).

From: Wolff Bock von Wülfingen ***@***.***>
Reply to: hallvard/plantuml ***@***.***>
Date: Wednesday, 7 April 2021 at 09:34
To: hallvard/plantuml ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hallvard/plantuml] Eclipse Marketplace Update (#125)


It seems that the version available via the marketplace is still 1.1.22 (or atleast it is what is offered in Eclipse 2021-03).
It would be great if you could update it, because i'm running into issues with https://github.com/plantuml-stdlib/C4-PlantUML where the include via URL doesn't work since they use tags which were added later to plantuml.

Small sidenote: In your readme.md you mention 1.1.25, but under releases there is only 1.1.24. Not clear to me if 1.1.25 is just what is currently worked on or if there is a release missing :)
