### ISSUE TITLE
Just interestede in puml files and comment extraction

### ISSUE THREAD

**Issue by zorce** [hallvard/plantuml#133]
Hi,

Currently working in a ansi C project and using eclipse derived application, installed the hallvard/plantuml plugin but having issues.
Cannot seem to generate any diagrams, nether from a simple textfile named tasks.puml (cause nullpointer exception) displayed below and also when adding the plantuml source within a comment in a c file. The plantuml source view is recognizing the source but without the @enduml tag but no image.

![image](https://user-images.githubusercontent.com/9129856/117252307-1056cd80-ae46-11eb-8d40-61e1ba183a7e.png)

**Comment by zorce** [comment]
And yes, graphviz is ok according to the properties
![image](https://user-images.githubusercontent.com/9129856/117252603-7e02f980-ae46-11eb-8542-dfd0577f2aba.png)

**Comment by hallvard** [comment]
Could you check the Error Log view and see if there's a stack trace there?

Somebody else has reported a similar issue, where the source diagram showed PlantUML code without the @enduml tag. This was apparently a line terminator issue, where my code didn't take into account that Windows uses two characters rather than just \n.

I've also seen a NullPointerException in non-java projects, perhaps there's a combination of problems.

**Comment by zorce** [comment]
Hi,
Here is the exported error log for the issue, maybe you get something out of this 🍡 
[eclipse_error.log](https://github.com/hallvard/plantuml/files/6433037/eclipse_error.log)

**Comment by hallvard** [comment]
I've encountered and fixed the NPE already. It happens when there's no path related to an editor, which I guess is when you created a new and untitled file, before you give it a name and save it. That is not related to the missing @enduml issue, which I think may be due to Windows' line endings.

Which OS are you using?

**Comment by zorce** [comment]
Did a drag and drop to from outside the project. When creating a new file inserting the bob -> alice demo it worked fine after saving the file. but seem to have to close/reopen the file for the rendering to kick in.

Now tried to add the same example in a c file within the comment.. but this is not recognized.

Running on windows 10 64bit

**Comment by hallvard** [comment]
I'll try to improve the handling of "foreign" files (the NPE is at least gone). I'll also look at the line ending problem. I'm closing this issue, since both are covered elsewhere.
