### ISSUE TITLE
Missing license files

### ISSUE THREAD

**Issue by davidjones7076** [hallvard/plantuml#2]
Hi,

Like the look of the eclipse plugin.

Are you willing to add the Apache 2.0 or LGPL license files to:
1. The eclipse plugin repo
2. THe jexercise repo
3. The update sites linked at http://plantuml.sourceforge.net/eclipse.html

Thanks,

David

**Comment by seiferma** [comment]
I am also highly interested in a clear license statement. This is not only important to allow extensions but also clarifies if commercial users are allowed to use your plugin.

Could you add a license to your work?

**Comment by arnaudroques** [comment]
If we are talking about the library plantuml.jar, the license is explained in the faq ( http://plantuml.com/faq.html ). If it's not clear, please tell us.

About the PlantUML Eclipse plugin, ( http://plantuml.sourceforge.net/eclipse.html ) the situation may indeed sound confuse. So we will add a LGPL notice in content.xml for http://plantuml.sourceforge.net/updatesite/ and http://plantuml.sourceforge.net/updatesitejuno/ starting for next version 8037.

Note that the repository https://github.com/hallvard/plantuml adds Ecore/Xcore support to the original PlantUML Eclipse plugin, and is not developped by the PlantUML team. However, we are going to send a mail to Hallvard Trætteberg which manages this repository so that licensing could be clarify.

**Comment by seiferma** [comment]
Thanks for your fast response. Indeed, for PlantUML itself the license is clear. A clear license statement for the original Eclipse plugin would already help a lot.

Is the source code for this plugin available anywhere (except from the outdated version in this repository)?

**Comment by arnaudroques** [comment]
Would a EPL license for the Eclipse Plugin be ok for you ? (Instead of LGPL as we have suggested before)

**Comment by seiferma** [comment]
EPL license would be great, as we also use EPL and would not have to consider compatibility of different licenses.

**Comment by arnaudroques** [comment]
We've just release V8037 and the corresponding Eclipse Plugin ( http://plantuml.sourceforge.net/updatesite/ and http://plantuml.sourceforge.net/updatesitejuno/ ) are clearly mentionning EPL license when beeing installed

**Comment by seiferma** [comment]
Thanks for clarifying this. Now even companties can use this plugin without running into legal issues.

Could you also provide a link to the according source code?

**Comment by arnaudroques** [comment]
Technically, we don't recompile the Eclipse Plugin when there is a new version of plantuml.jar. We are just repackaging the 1.1.8 plugin with the new plantuml.jar and we published it on sourceforge.

So the according source code corresponds to this commit :
https://github.com/hallvard/plantuml/commit/c76bfc85f82d74cc9ef5648f82deaa604fecfc46
(Except that version and plantuml.jar is changed).
Further commits (that are adding ecore support) are not included in the published version.

Hope this helps!

**Comment by seiferma** [comment]
Thanks, but your link does not point to the most recent source code of the plugin itself. This repository is not sufficient because it does not include several bug fixes that you included into the original plugin. I cannot find the source code of your original plugin.

Could you provide this link?
