### ISSUE TITLE
PlantUML view is not updated if the editor with PlantUML comments moved to other eclipse window

### ISSUE THREAD

**Issue by anb0s** [hallvard/plantuml#20]
If the editor with PlantUML comments is attached to the main Eclipse window the PlantUML view shows and refreshes the diagram -> OK

If the editor is moved outside of the main Eclipse window (detached or attached to another window at second monitor) the the PlantUML view shows the diagram but does not refresh it anymore.

**Comment by hallvard** [comment]
This may be the same issue as #13, which is fixed in the latest version (from yesterday). The problem was that diagram update was triggered when an editor was made topmost within a stack, not when it was activated. Hence, if you activated an editor that was already topmost, the diagram didn't update. Could you try the latest version and see if your problem is still there?

**Comment by anb0s** [comment]
The new version 1.1.14.8059 works like expected. Thanks!
