### ISSUE TITLE
Automatic export

### ISSUE THREAD

**Issue by Flowkap** [hallvard/plantuml#41]
Ist it possible to configure an automatic export on build events or on save to a specified puml file?

Anyway thanks for the plugin!

**Comment by hallvard** [comment]
I'm not sure I understand what you mean. Do you mean export to an _image file_ whenever the file from which it was _derived/generated_ changes? What do you think of the following behaviour: Have an **auto-export** flag in the preferences. When it is _set_, whenever a file changes that has a _corresponding_ image file (previously) generated by plantuml in the same folder, _re-generate_ the image.

**Comment by Flowkap** [comment]
Yeah for example. 

Nice would be also to select which format ( not only images but raw puml for example) 

Some more questions in general:
Are there settings already? 
How to access them? 
Can I limit which classes from ecore (default are all)?
Is automation by maven or gradle possible? 

Thanks for the quick reply anyway :)

**Comment by hallvard** [comment]
The format should be derived from the file extension when you save the diagram. If the file extension is puml or plantuml, the diagram source is saved, otherwise the image.

The preferences are those provided by Eclipse, e.g. Window -> Preferences on Windows, Command-, on Mac.

If you want to limit which classes to generate from an Ecore file, please create another issue.

**Comment by paulvi** [comment]
I second this. The should be an option, that 

for `somefile.puml` file on save a `somefile.png` is created/updated.

This is good to commit to version control, and other teammates do not need to install plugin to view.
The png can be inlined in markdown, javadoc without extra build steps.

**Comment by dvojtise** [comment]
another good scenario where this automatic png export would be useful:
https://github.com/de-jcup/eclipse-asciidoctor-editor/issues/98 

Ie. if an asciidoc uses normal import for images rather than embedded plantuml, then the asciidoc preview will be correct too.

**Comment by dvojtise** [comment]
@paulvi  However, there is one drawback when using exporting png **and** saving them in the versioning system.
due to user environment issue such as: http://forum.plantuml.net/5425/relation-long-with-graphviz-using-labels-relations-namespace, the png file may vary between 2 users without  any change in the puml file
:disappointed:

**Comment by Flowkap** [comment]
You don't need to save them in git but auto save would be extremely convenient.

**Comment by dvojtise** [comment]
Aggreed, I do think autogeneration of png is useful, 
only  storing it  in git may raise issue (and would require a good .gitignore to avoid flaky changes)
